//! Commands for viewing and managing the content files inside an instance —
//! mods, resource packs, and shader packs — directly on disk. This is the source
//! of truth (it also surfaces files a modpack dropped in that aren't tracked in
//! the database), so enable/disable/remove operate on the files themselves.

use std::fs;
use std::io::Read;
use std::path::{Path, PathBuf};

use base64::Engine;

use crate::download::safe_join;
use crate::dto::instance::{ContentEntry, ContentMeta, InstanceContent};
use crate::instances::paths::instance_root;
use tauri::State;

use super::search::AppState;

const DISABLED_SUFFIX: &str = ".disabled";

/// A mod's own declared display name and embedded icon, read from its jar
/// metadata in one pass. Best-effort: any missing/unreadable/malformed
/// metadata just leaves the field `None` (name falls back to the
/// filename-derived name on the frontend; icon falls back to a DB-recorded
/// one, if any).
struct ModMeta {
    name: Option<String>,
    icon: Option<String>,
}

/// Reads name + icon from a jar's Fabric/Quilt, Forge/NeoForge, or legacy
/// Forge metadata. Opens the zip archive once and reuses it for both lookups
/// instead of the two separate full re-parses this used to do per mod.
fn read_mod_metadata(jar_path: &Path) -> ModMeta {
    let mut meta = ModMeta { name: None, icon: None };
    let Ok(file) = fs::File::open(jar_path) else {
        return meta;
    };
    let Ok(mut archive) = zip::ZipArchive::new(file) else {
        return meta;
    };

    // Fabric / Quilt.
    if let Some(contents) = read_zip_entry(&mut archive, "fabric.mod.json") {
        if let Ok(value) = serde_json::from_str::<serde_json::Value>(&contents) {
            meta.name = non_empty(value.get("name").and_then(|v| v.as_str()));
            let icon_path = match value.get("icon") {
                Some(serde_json::Value::String(path)) => non_empty(Some(path)),
                Some(serde_json::Value::Object(sizes)) => sizes
                    .values()
                    .filter_map(|v| v.as_str())
                    .last()
                    .and_then(|path| non_empty(Some(path))),
                _ => None,
            };
            if let Some(path) = icon_path {
                meta.icon = read_zip_image_entry(&mut archive, &path);
            }
        }
    }

    // Forge / NeoForge. NeoForge 1.20.5+ renamed this file to
    // `neoforge.mods.toml`; mods built only for modern NeoForge (the vast
    // majority of a current NeoForge pack) never ship the old `mods.toml` at
    // all, so both names need checking. Same schema either way — NeoForge is
    // a Forge fork — and neoforge.mods.toml takes priority when both exist,
    // same as the loader itself resolves it.
    if meta.name.is_none() || meta.icon.is_none() {
        for entry_name in ["META-INF/neoforge.mods.toml", "META-INF/mods.toml"] {
            if meta.name.is_some() && meta.icon.is_some() {
                break;
            }
            let Some(contents) = read_zip_entry(&mut archive, entry_name) else {
                continue;
            };
            let Ok(value) = toml::from_str::<toml::Value>(&contents) else {
                continue;
            };
            let first_mod = value.get("mods").and_then(|m| m.as_array()).and_then(|a| a.first());
            if meta.name.is_none() {
                meta.name = non_empty(
                    first_mod
                        .and_then(|m| m.get("displayName"))
                        .and_then(|v| v.as_str()),
                );
            }
            if meta.icon.is_none() {
                // `logoFile` is documented as a top-level key (applies to
                // the whole file), but some mods — notably ones generated by
                // Modrinth's packwiz/template tooling — declare it per-mod
                // inside the `[[mods]]` entry instead. Both are seen in the
                // wild, so check the per-mod entry as a fallback.
                let logo = value
                    .get("logoFile")
                    .and_then(|v| v.as_str())
                    .or_else(|| first_mod.and_then(|m| m.get("logoFile")).and_then(|v| v.as_str()));
                if let Some(logo) = non_empty(logo) {
                    // The toml comment calls this "root of the jar", but in
                    // practice a lot of build tooling (ForgeGradle/NeoGradle)
                    // packages the logo next to mods.toml itself instead —
                    // i.e. under META-INF/ — so a plain filename commonly
                    // only resolves there, not at the jar root.
                    meta.icon = read_zip_image_entry(&mut archive, &logo)
                        .or_else(|| read_zip_image_entry(&mut archive, &format!("META-INF/{logo}")));
                }
            }
        }
    }

    // Legacy Forge (1.12 and earlier) — name only, no icon convention.
    if meta.name.is_none() {
        if let Some(contents) = read_zip_entry(&mut archive, "mcmod.info") {
            if let Ok(value) = serde_json::from_str::<serde_json::Value>(&contents) {
                let first = value.as_array().and_then(|arr| arr.first()).or_else(|| {
                    value.get("modList").and_then(|v| v.as_array()).and_then(|arr| arr.first())
                });
                meta.name = non_empty(first.and_then(|m| m.get("name")).and_then(|v| v.as_str()));
            }
        }
    }

    meta
}

fn read_zip_entry<R: std::io::Read + std::io::Seek>(
    archive: &mut zip::ZipArchive<R>,
    entry_name: &str,
) -> Option<String> {
    let mut entry = archive.by_name(entry_name).ok()?;
    let mut contents = String::new();
    entry.read_to_string(&mut contents).ok()?;
    Some(contents)
}

/// Reads a resource pack's `pack.png`, the standard convention for its icon.
fn read_resourcepack_icon(zip_path: &Path) -> Option<String> {
    let file = fs::File::open(zip_path).ok()?;
    let mut archive = zip::ZipArchive::new(file).ok()?;
    read_zip_image_entry(&mut archive, "pack.png")
}

fn read_zip_image_entry<R: std::io::Read + std::io::Seek>(
    archive: &mut zip::ZipArchive<R>,
    entry_name: &str,
) -> Option<String> {
    let mut entry = archive.by_name(entry_name).ok()?;
    let mut bytes = Vec::new();
    entry.read_to_end(&mut bytes).ok()?;
    if bytes.is_empty() {
        return None;
    }
    let mime = match Path::new(entry_name)
        .extension()
        .and_then(|e| e.to_str())
        .map(str::to_lowercase)
        .as_deref()
    {
        Some("jpg") | Some("jpeg") => "image/jpeg",
        Some("gif") => "image/gif",
        _ => "image/png",
    };
    let encoded = base64::engine::general_purpose::STANDARD.encode(&bytes);
    Some(format!("data:{mime};base64,{encoded}"))
}

fn non_empty(value: Option<&str>) -> Option<String> {
    let trimmed = value?.trim();
    if trimmed.is_empty() {
        None
    } else {
        Some(trimmed.to_string())
    }
}

/// Map a category slug to its folder name inside the instance.
fn category_dir(category: &str) -> Result<&'static str, String> {
    match category {
        "mod" => Ok("mods"),
        "resourcepack" => Ok("resourcepacks"),
        "shaderpack" => Ok("shaderpacks"),
        other => Err(format!("Unknown content category '{other}'.")),
    }
}

/// A directory entry before any metadata-cache join — just what a plain
/// `read_dir` + `metadata()` call gives us. `mtime_unix` never leaves the
/// backend (not part of `ContentEntry`'s wire shape); it exists purely to
/// fingerprint the file against the cache below.
struct ScannedFile {
    file_name: String,
    enabled: bool,
    size_bytes: u64,
    mtime_unix: i64,
}

/// Lists files in a content directory with no jar/zip parsing at all — just
/// names, sizes, and mtimes off the filesystem, so this is effectively
/// instant even for an instance with hundreds of mods. Only files with
/// `expected_ext` (the extension the loader itself actually reads from this
/// folder — `.jar` for mods, `.zip` for resource/shader packs) are listed;
/// a stray readme or changelog a shader/resource pack's own CurseForge page
/// bundles alongside the real archive is never something Forge/Iris loads,
/// so it's clutter, not content.
fn scan_dir(dir: &Path, expected_ext: &str) -> Vec<ScannedFile> {
    let mut out = Vec::new();
    let Ok(entries) = fs::read_dir(dir) else {
        return out;
    };
    for entry in entries.flatten() {
        let raw = entry.file_name().to_string_lossy().to_string();
        // Skip our own staging file and hidden dotfiles.
        if raw.starts_with('.') {
            continue;
        }
        let (file_name, enabled) = match raw.strip_suffix(DISABLED_SUFFIX) {
            Some(base) => (base.to_string(), false),
            None => (raw.clone(), true),
        };
        // A resource/shader pack can be an unzipped folder — that's still
        // real content, just not archived — so only files (never
        // directories) are held to the extension check.
        let is_dir = entry.file_type().map(|t| t.is_dir()).unwrap_or(false);
        if !is_dir && !file_name.to_ascii_lowercase().ends_with(expected_ext) {
            continue;
        }
        let metadata = entry.metadata().ok();
        let size_bytes = metadata.as_ref().map(|m| m.len()).unwrap_or(0);
        let mtime_unix = metadata
            .and_then(|m| m.modified().ok())
            .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);
        out.push(ScannedFile { file_name, enabled, size_bytes, mtime_unix });
    }
    out.sort_by(|a, b| a.file_name.to_lowercase().cmp(&b.file_name.to_lowercase()));
    out
}

/// Joins a directory's scanned files against the instance's metadata cache —
/// a file whose current size+mtime match a cached row gets its name/icon
/// filled in right here, with zero jar/zip parsing, and is marked
/// `meta_resolved` so the frontend never fetches it again. A file that's new
/// or has changed since it was last cached is left unresolved for the
/// existing per-row lazy fetch to pick up (which then populates the cache
/// for next time).
fn apply_cache(
    files: Vec<ScannedFile>,
    category: &str,
    cache: &std::collections::HashMap<(String, String), crate::db::CachedContentMeta>,
) -> Vec<ContentEntry> {
    files
        .into_iter()
        .map(|f| {
            let hit = cache
                .get(&(category.to_string(), f.file_name.clone()))
                .filter(|c| c.size_bytes == f.size_bytes && c.mtime_unix == f.mtime_unix);
            ContentEntry {
                file_name: f.file_name,
                name: hit.and_then(|c| c.name.clone()),
                icon: hit.and_then(|c| c.icon.clone()),
                enabled: f.enabled,
                size_bytes: f.size_bytes,
                meta_resolved: hit.is_some(),
            }
        })
        .collect()
}

#[tauri::command]
pub async fn list_instance_content(
    state: State<'_, AppState>,
    instance_id: String,
) -> Result<InstanceContent, String> {
    let t0 = std::time::Instant::now();
    let root = instance_root(&instance_id).map_err(|e| e.to_string())?;
    let cache_rows = state.db.get_content_meta_cache(&instance_id).unwrap_or_default();
    let cache: std::collections::HashMap<(String, String), _> = cache_rows
        .into_iter()
        .map(|c| ((c.category.clone(), c.file_name.clone()), c))
        .collect();

    // Directory listing + cache join — no jar/zip parsing for anything
    // already seen before — so this stays fast no matter how big the pack
    // is. Still off the async runtime since it's real disk + DB I/O.
    let result = tauri::async_runtime::spawn_blocking(move || InstanceContent {
        mods: apply_cache(scan_dir(&root.join("mods"), ".jar"), "mod", &cache),
        resource_packs: apply_cache(scan_dir(&root.join("resourcepacks"), ".zip"), "resourcepack", &cache),
        shader_packs: apply_cache(scan_dir(&root.join("shaderpacks"), ".zip"), "shaderpack", &cache),
    })
    .await
    .map_err(|e| e.to_string());

    match &result {
        Ok(content) => crate::activity::append_log(
            &format!(
                "list_instance_content OK elapsed={}ms mods={} packs={} shaders={} instance={instance_id}",
                t0.elapsed().as_millis(),
                content.mods.len(),
                content.resource_packs.len(),
                content.shader_packs.len(),
            ),
            "debug",
            None,
        ),
        Err(e) => crate::activity::append_log(
            &format!(
                "list_instance_content ERR elapsed={}ms err={e} instance={instance_id}",
                t0.elapsed().as_millis(),
            ),
            "debug",
            None,
        ),
    }
    result
}

/// Locate a content file on disk given its display name (enabled or disabled).
/// `file_name` is frontend-supplied, so it's resolved through `safe_join`
/// rather than trusted as a plain path segment.
fn resolve_file(dir: &Path, file_name: &str) -> Option<PathBuf> {
    let enabled = safe_join(dir, file_name).ok()?;
    if enabled.exists() {
        return Some(enabled);
    }
    let disabled = safe_join(dir, &format!("{file_name}{DISABLED_SUFFIX}")).ok()?;
    if disabled.exists() {
        return Some(disabled);
    }
    None
}

/// Resolves one file's display name + icon by opening just that jar/zip —
/// the frontend calls this per row as it scrolls into view, instead of the
/// whole instance paying for every file's metadata up front.
#[tauri::command]
pub async fn get_content_meta(
    state: State<'_, AppState>,
    instance_id: String,
    category: String,
    file_name: String,
) -> Result<ContentMeta, String> {
    let root = instance_root(&instance_id).map_err(|e| e.to_string())?;
    let dir = root.join(category_dir(&category)?);
    let Some(path) = resolve_file(&dir, &file_name) else {
        return Ok(ContentMeta::default());
    };
    let is_jar = file_name.to_lowercase().ends_with(".jar");
    let is_zip = file_name.to_lowercase().ends_with(".zip");

    // Icon recorded when this mod was installed via Browse, used as a
    // fallback when the jar doesn't embed its own icon. A single-row lookup
    // rather than `list_instance_mods` — this runs once per row as the
    // Content tab scrolls, and re-fetching the whole instance's mod table
    // for every single row was O(n) work repeated n times.
    let db_icon = if category == "mod" {
        state
            .db
            .get_instance_mod_icon_by_file(&instance_id, &file_name)
            .unwrap_or(None)
    } else {
        None
    };

    // Fingerprinted before the parse so the cache write below lines up with
    // exactly the bytes that were just read — a file that changes between
    // this stat and the parse just means one stale cache write, corrected
    // the next time this file's row is fetched.
    let fingerprint = fs::metadata(&path).ok().map(|m| {
        let mtime_unix = m
            .modified()
            .ok()
            .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);
        (m.len(), mtime_unix)
    });
    let category_for_cache = category.clone();
    let file_name_for_cache = file_name.clone();

    let meta = tauri::async_runtime::spawn_blocking(move || match category.as_str() {
        "mod" if is_jar => {
            let meta = read_mod_metadata(&path);
            ContentMeta {
                name: meta.name,
                icon: meta.icon.or(db_icon),
            }
        }
        "resourcepack" if is_zip => ContentMeta {
            name: None,
            icon: read_resourcepack_icon(&path),
        },
        _ => ContentMeta::default(),
    })
    .await
    .map_err(|e| e.to_string())?;

    // Cached so the next time this instance's Content tab opens, this exact
    // file (unchanged) needs no jar/zip parsing at all — including when
    // parsing found nothing, so a jar with no embedded icon isn't reopened
    // forever looking for one it doesn't have.
    if let Some((size_bytes, mtime_unix)) = fingerprint {
        let _ = state.db.upsert_content_meta_cache(
            &instance_id,
            &category_for_cache,
            &file_name_for_cache,
            size_bytes,
            mtime_unix,
            meta.name.as_deref(),
            meta.icon.as_deref(),
        );
    }

    Ok(meta)
}

#[tauri::command]
pub fn set_content_enabled(
    _state: State<'_, AppState>,
    instance_id: String,
    category: String,
    file_name: String,
    enabled: bool,
) -> Result<(), String> {
    let root = instance_root(&instance_id).map_err(|e| e.to_string())?;
    let dir = root.join(category_dir(&category)?);
    let current = resolve_file(&dir, &file_name)
        .ok_or_else(|| format!("'{file_name}' was not found in this instance."))?;

    let target = if enabled {
        safe_join(&dir, &file_name).map_err(|e| e.to_string())?
    } else {
        safe_join(&dir, &format!("{file_name}{DISABLED_SUFFIX}")).map_err(|e| e.to_string())?
    };
    if current != target {
        fs::rename(&current, &target).map_err(|e| e.to_string())?;
    }
    Ok(())
}

#[tauri::command]
pub fn remove_content_file(
    state: State<'_, AppState>,
    instance_id: String,
    category: String,
    file_name: String,
) -> Result<(), String> {
    let root = instance_root(&instance_id).map_err(|e| e.to_string())?;
    let dir = root.join(category_dir(&category)?);
    let file = resolve_file(&dir, &file_name)
        .ok_or_else(|| format!("'{file_name}' was not found in this instance."))?;

    if file.is_dir() {
        fs::remove_dir_all(&file).map_err(|e| e.to_string())?;
    } else {
        fs::remove_file(&file).map_err(|e| e.to_string())?;
    }

    // Best-effort: drop any tracked mod row pointing at this file.
    if category == "mod" {
        let _ = state.db.delete_instance_mod_by_file(&instance_id, &file_name);
    }
    Ok(())
}

#[cfg(test)]
mod content_meta_cache_tests {
    use super::{apply_cache, ScannedFile};
    use crate::db::CachedContentMeta;
    use std::collections::HashMap;

    fn cache_row(category: &str, file_name: &str, size_bytes: u64, mtime_unix: i64, name: Option<&str>, icon: Option<&str>) -> CachedContentMeta {
        CachedContentMeta {
            category: category.to_string(),
            file_name: file_name.to_string(),
            size_bytes,
            mtime_unix,
            name: name.map(str::to_string),
            icon: icon.map(str::to_string),
        }
    }

    #[test]
    fn matching_fingerprint_is_resolved_from_cache_with_no_parsing() {
        let scanned = vec![ScannedFile {
            file_name: "Foo.jar".to_string(),
            enabled: true,
            size_bytes: 100,
            mtime_unix: 1000,
        }];
        let mut cache = HashMap::new();
        cache.insert(
            ("mod".to_string(), "Foo.jar".to_string()),
            cache_row("mod", "Foo.jar", 100, 1000, Some("Foo Mod"), Some("data:image/png;base64,x")),
        );

        let entries = apply_cache(scanned, "mod", &cache);

        assert!(entries[0].meta_resolved, "matching size+mtime should count as a cache hit");
        assert_eq!(entries[0].name.as_deref(), Some("Foo Mod"));
        assert_eq!(entries[0].icon.as_deref(), Some("data:image/png;base64,x"));
    }

    #[test]
    fn changed_file_invalidates_the_cache_entry() {
        let scanned = vec![ScannedFile {
            file_name: "Foo.jar".to_string(),
            enabled: true,
            size_bytes: 200, // different size than the cached row
            mtime_unix: 1000,
        }];
        let mut cache = HashMap::new();
        cache.insert(
            ("mod".to_string(), "Foo.jar".to_string()),
            cache_row("mod", "Foo.jar", 100, 1000, Some("Foo Mod"), None),
        );

        let entries = apply_cache(scanned, "mod", &cache);

        assert!(!entries[0].meta_resolved, "a changed file must not be served stale cached metadata");
        assert_eq!(entries[0].name, None);
    }

    #[test]
    fn cached_no_icon_result_still_counts_as_resolved() {
        // A jar with no embedded icon at all was already parsed once and the
        // cache correctly recorded "nothing found" — that must still skip
        // the per-row fetch, not look indistinguishable from "never checked".
        let scanned = vec![ScannedFile {
            file_name: "NoIcon.jar".to_string(),
            enabled: true,
            size_bytes: 50,
            mtime_unix: 500,
        }];
        let mut cache = HashMap::new();
        cache.insert(
            ("mod".to_string(), "NoIcon.jar".to_string()),
            cache_row("mod", "NoIcon.jar", 50, 500, Some("No Icon Mod"), None),
        );

        let entries = apply_cache(scanned, "mod", &cache);

        assert!(entries[0].meta_resolved);
        assert_eq!(entries[0].icon, None);
    }

    #[test]
    fn unseen_file_is_left_unresolved() {
        let scanned = vec![ScannedFile {
            file_name: "New.jar".to_string(),
            enabled: true,
            size_bytes: 10,
            mtime_unix: 10,
        }];
        let entries = apply_cache(scanned, "mod", &HashMap::new());

        assert!(!entries[0].meta_resolved);
        assert_eq!(entries[0].name, None);
        assert_eq!(entries[0].icon, None);
    }
}
