import type { McOptions } from "./types";

/** Minecraft default key codes (options.txt `key_key.*` values). */
export const DEFAULT_KEY_BINDINGS: Record<string, string> = {
  attack: "key.mouse.left",
  use: "key.mouse.right",
  forward: "key.keyboard.w",
  left: "key.keyboard.a",
  back: "key.keyboard.s",
  right: "key.keyboard.d",
  jump: "key.keyboard.space",
  sneak: "key.keyboard.left.shift",
  sprint: "key.keyboard.left.control",
  drop: "key.keyboard.q",
  inventory: "key.keyboard.e",
  chat: "key.keyboard.t",
  playerlist: "key.keyboard.tab",
  pickItem: "key.mouse.middle",
  command: "key.keyboard.slash",
  socialInteractions: "key.keyboard.p",
  screenshot: "key.keyboard.f2",
  togglePerspective: "key.keyboard.f5",
  smoothCamera: "key.keyboard.unknown",
  fullscreen: "key.keyboard.f11",
  spectatorOutlines: "key.keyboard.unknown",
  swapOffhand: "key.keyboard.f",
  saveToolbarActivator: "key.keyboard.c",
  loadToolbarActivator: "key.keyboard.x",
  advancements: "key.keyboard.l",
  "hotbar.1": "key.keyboard.1",
  "hotbar.2": "key.keyboard.2",
  "hotbar.3": "key.keyboard.3",
  "hotbar.4": "key.keyboard.4",
  "hotbar.5": "key.keyboard.5",
  "hotbar.6": "key.keyboard.6",
  "hotbar.7": "key.keyboard.7",
  "hotbar.8": "key.keyboard.8",
  "hotbar.9": "key.keyboard.9",
};

export const KEY_BINDING_LABELS: Record<string, string> = {
  attack: "Attack / destroy",
  use: "Use item / place block",
  forward: "Walk forward",
  left: "Strafe left",
  back: "Walk backward",
  right: "Strafe right",
  jump: "Jump",
  sneak: "Sneak",
  sprint: "Sprint",
  drop: "Drop item",
  inventory: "Open inventory",
  chat: "Open chat",
  playerlist: "Player list",
  pickItem: "Pick block",
  command: "Open command",
  socialInteractions: "Social interactions",
  screenshot: "Take screenshot",
  togglePerspective: "Toggle perspective",
  smoothCamera: "Toggle cinematic camera",
  fullscreen: "Toggle fullscreen",
  spectatorOutlines: "Spectator outlines",
  swapOffhand: "Swap offhand item",
  saveToolbarActivator: "Save hotbar",
  loadToolbarActivator: "Load hotbar",
  advancements: "Advancements",
  "hotbar.1": "Hotbar slot 1",
  "hotbar.2": "Hotbar slot 2",
  "hotbar.3": "Hotbar slot 3",
  "hotbar.4": "Hotbar slot 4",
  "hotbar.5": "Hotbar slot 5",
  "hotbar.6": "Hotbar slot 6",
  "hotbar.7": "Hotbar slot 7",
  "hotbar.8": "Hotbar slot 8",
  "hotbar.9": "Hotbar slot 9",
};

export function defaultMcOptions(): McOptions {
  return {
    customize: true,
    fullscreen: false,
    viewBobbing: true,
    guiScale: 2,
    gamma: 50,
    renderDistance: 12,
    simulationDistance: 12,
    fov: 70,
    entityShadows: true,
    vsync: true,
    maxFps: 260,
    graphicsMode: "fancy",
    clouds: "fancy",
    particles: "all",
    mipmapLevels: 4,
    entityDistanceScaling: 100,
    biomeBlendRadius: 2,
    autoJump: false,
    invertMouse: false,
    mouseSensitivity: 50,
    rawMouseInput: true,
    discreteMouseScroll: false,
    toggleSprint: false,
    toggleCrouch: false,
    showSubtitles: false,
    reducedDebugInfo: false,
    narrator: "off",
    language: "en_us",
    masterVolume: 100,
    musicVolume: 100,
    jukeboxVolume: 100,
    weatherVolume: 100,
    blocksVolume: 100,
    hostileVolume: 100,
    neutralVolume: 100,
    playerVolume: 100,
    ambientVolume: 100,
    voiceVolume: 100,
    keyBindings: { ...DEFAULT_KEY_BINDINGS },
  };
}

export function normalizeMcOptions(partial: Partial<McOptions>): McOptions {
  const defaults = defaultMcOptions();
  return {
    ...defaults,
    ...partial,
    keyBindings: {
      ...DEFAULT_KEY_BINDINGS,
      ...defaults.keyBindings,
      ...partial.keyBindings,
    },
  };
}
